FROM node:18-alpine

ARG HOST_SRC_ROOT
ARG APP_ROOT
ENV APP_ROOT=$APP_ROOT

WORKDIR $APP_ROOT

COPY ${HOST_SRC_ROOT}/package*.json $APP_ROOT/

RUN npm install

COPY ${HOST_SRC_ROOT} $APP_ROOT

CMD ["npm", "run", "dev"]