# Help Command
.PHONY: help

help:
	@echo "Available commands:"
	@echo ""
	@echo "## Setup Commands"
	@echo "  make init-config  - Apply git configuration from template"
	@echo "  make init-dev     - Initial setup for development (first time only)"
	@echo "  make init-hooks   - Install git hooks (pre-commit: sort:imports (import sorting and auto-fix))"
	@echo ""
	@echo "## Development Commands"
	@echo "  make dev          - Start development server"
	@echo "  make down         - Stop Docker containers"
	@echo "  make ps           - List running containers"
	@echo "  make npminstall   - Install npm dependencies"
	@echo "  make storybook    - Start Storybook development server"
	@echo ""
	@echo "## Testing Commands"
	@echo "  make unit         - Run unit tests only"
	@echo "  make e2e          - Run E2E tests only"
	@echo "  make testall      - Run all tests (unit + E2E)"
	@echo "  make testcheck    - Run tests with warnings"
	@echo "  make testlint     - Run comprehensive tests and linting (required before PR)"
	@echo ""
	@echo "## Code Quality Commands"
	@echo "  make check        - Run compile, knip, tsr, and lint checks"
	@echo "  make sortimports  - Sort imports in all files"
	@echo "  make lintmd       - Run markdownlint for Markdown files"
	@echo "  make lintmdfix    - Run markdownlint with auto-fix"
	@echo ""
	@echo "## Git Utility Commands"
	@echo "  make git-list-unmerged - List all branches not merged into develop"
	@echo ""
	@echo "## Git Worktree Commands"
	@echo "  make wt-list      - List all git worktrees"
	@echo "  make wt-add       - Add a new worktree (usage: make wt-add BRANCH=branch-name)"
	@echo "  make wt-remove    - Remove a worktree (usage: make wt-remove BRANCH=branch-name)"
	@echo "  make wt-prune     - Prune stale worktree references"
	@echo "  make wt-current   - Show the currently active worktree"
	@echo "  make wt-dev       - Start development server for worktree (usage: make wt-dev BRANCH=branch-name)"
	@echo "  make wt-down      - Stop worktree Docker containers"
	@echo "  make wt-up        - Start worktree Docker containers"
	@echo "  make wt-disable   - Disable worktree mode, return to main repository"
	@echo ""
	@echo "  make help         - Show this help message"
